---
- name: Install and Configure Suricata
  hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  vars_files:
    - vars/suricata_vars.yaml
  tasks:
    - include: tasks/suricata.yaml
