---

# Configure Suricata
- name: Configure Suricata
  block:
  - name: Suricata config
    template:
      src: './templates/suricata.yaml.j2'
      dest: "{{ default_conf_dir }}/suricata.yaml"

# Create a Welcome page
- name: Copying welcome page
  copy:
    src: index.html
    dest: /var/www/html/

# Start Services
- name: Starting httpd services
  service:
    name: "httpd"
    state: started
    enabled: yes

- name: Starting Suricata services
  service:
    name: "suricata"
    state: started
    enabled: yes

