---
# Install EPEL repository
- name: Install the EPEL release package
  command: amazon-linux-extras install epel -y

# Install Suricata
- name: Install Suricata
  yum:
    name: "suricata"
    state: present

# Install Apache Web Server
- name: Install Apache Web Server
  yum:
    name: "httpd"
    state: present

# Install CloudWatch Log Agent
- name: Install CloudWatch Log Agent
  yum:
    name: awslogs
    state: present


